### ISSUE TITLE
在 Chrome 上显示空白

### ISSUE THREAD

**Issue by baurine** [love2io/Love2.io#12]
<img width="720" alt="qq20180103-2" src="https://user-images.githubusercontent.com/1284531/34517750-54c4dcc8-f0b7-11e7-9a1c-3e609fb4a16e.png">

如截图所示，在 Chrome 最新版加载一片空白，console 里打印错误信息。

在 Firefox 最新版工作正常。

**Comment by love2io** [comment]
@baurine 谢谢您的反馈，我升级到最新版 『版本 63.0.3239.108（正式版本） （64 位）』并没有发现空白的问题，请问您具体是那个版本

**Comment by baurine** [comment]
@love2io ，之前的版本是 63.0.3239.84，然后刚刚升到了 63.0.3239.108，系统是 macOS High Sierra，还是一样的问题。但是我也比较纳闷，昨天在一台系统为 macOS EI Captain 的 iMac 上的 Chrome 打开却是正常的。两个 Chrome 因为使用了 google 账户同步，安装的插件也是一样的。

貌似只有我这遇到了，那就先放一边吧，等你有时间再看，或者我看看 console log 能不能再找出点线索。

**Comment by baurine** [comment]
`Mixed Content: The page at 'https://love2.io/' was loaded over HTTPS, but requested an insecure script 'http://cdn.staticfile.org/react-router/3.0.0/ReactRouter.min.js?_veri=20121009'. This request has been blocked; the content must be served over HTTPS.`

你的代码里哪个地方有加载 http://cdn.staticfile.org/react-router/3.0.0/ReactRouter.min.js?_veri=20121009 这个库吗？

**Comment by love2io** [comment]
好的，我会关注下，有关任何新的线索还麻烦反馈下，谢谢！

**Comment by love2io** [comment]
https://cdn.staticfile.org/react-router/3.0.0/ReactRouter.min.js 代码里面加载的是这个，应该是https的
